version: '2'
services:
  web:
    build: .
    depends_on:
     - mysql
     - memcached
    ports:
     - "8000:8000"
    volumes:
     - ./app:/usr/src/lumen/app
     - ./bootstrap:/usr/src/lumen/bootstrap
     - ./database:/usr/src/lumen/database
     - ./public:/usr/src/lumen/public
     - ./resources:/usr/src/lumen/resources
     - ./routes:/usr/src/lumen/routes
     - ./storage:/usr/src/lumen/storage

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextweb
      MYSQL_USER: nextweb
      MYSQL_PASSWORD: nextweb
    ports:
     - "3306:3306"

  memcached:
    image: memcached:latest
