version: '2'
services:
  web:
    build: .
    depends_on:
     - mysql
     - memcached
    ports:
     - "8000:8000"
    volumes:
     - ./app:/var/www/html/app
     - ./bootstrap:/var/www/html/bootstrap
     - ./database:/var/www/html/database
     - ./public:/var/www/html/public
     - ./resources:/var/www/html/resources
     - ./routes:/var/www/html/routes
     - ./storage:/var/www/html/storage

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextweb
      MYSQL_USER: nextweb
      MYSQL_PASSWORD: nextweb
    ports:
     - "3306:3306"

  memcached:
    image: memcached:latest
